export const expressions = [
  "¡AH! Acabaramos!",
  "Ejem",
  "No, home no...",
  "Cal?",
  "EXPRESIONES",
  "¿Tienes las devtools cerradas?",
  "¿Os imagináis que alguien este programando sin estar compilando al mismo tiempo?",
  "LA CAJA DE LEGO",
  "¿Qué devuelve una función?",
  "Ahí está el tío",
  "Espero que lo tengáis en rojo y en grande en TODAS las páginas de vuestros apuntes",
  "Y...... SE ACABÓ",
  "Os echan eh! si respondéis esto os echan de la empresa!",
  "¿Challengesito?",
  "Mentir está feo",
  "Llavors, semillas",
  "Mario bug",
];
